### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by Kevyunsun** [conallwang/NPVA#1]
I love what you made here. I'm curious... What is needed to train a model? And is there a program that can be used to replicate facial movements etc in real time using this?

**Comment by conallwang** [comment]
Thanks!

**Comment by conallwang** [comment]
Thanks!

Basically, training our models needs calibrated multi-view images (~40 views for our results), topologically consistent coarse meshes and unwarpped UV texture maps for each frame. To restore details in the mouth and eyes, we also derive depth maps from multi-view images for supervision as described in Sec. 4 of our paper.

Using current codes, you can only driving the head avatar with coarse meshes and avg. texture map as inputs. But if you hope any other driving signals (e.g., VR Headset frames, FLAME params, or audios), you need to train an additional network to map the driving signals to our learned latent space and then use our pretrained decoder to decode the latent code. "Deep appearance models for face rendering, SIGGRAPH 2018"(https://dl.acm.org/doi/10.1145/3197517.3201401) provides an alternative methods to take the VR Headset frames as the driving signal.

**Comment by conallwang** [comment]
Thanks!

Basically, training our models needs calibrated multi-view images (~40 views for our results), topologically consistent coarse meshes and unwarpped UV texture maps for each frame. To restore details in the mouth and eyes, we also derive depth maps from multi-view images for supervision as described in Sec. 4 of our paper.

Using current codes, you can only driving the head avatar with coarse meshes and avg. texture map as inputs. But if you hope any other driving signals (e.g., VR Headset frames, FLAME params, or audios), you need to train an additional network to map the driving signals to our learned latent space and then use our pretrained decoder to decode the latent code. "Deep appearance models for face rendering, SIGGRAPH 2018"(https://dl.acm.org/doi/10.1145/3197517.3201401) provides an alternative methods to take the VR Headset frames as the driving signal. Maybe I will provide a program to drive our NPVA using FLAME params and make it easy to use, if I had some free time.

Good questions, and hope my answers helps  :)

Cong
